---
title: "BC big game harvesting"
output: html_notebook
# output: 
#   flexdashboard::flex_dashboard
#   #flexdashboard::flex_dashboard:
#     #orientation: columns
---

<!-- 
Execute a chunk: click the *Run* button within the chunk or place your cursor inside it and press *Ctrl+Shift+Enter*.

Add a new chunk:  click the *Insert Chunk* button on the toolbar or press *Ctrl+Alt+I*.

This notebook analyzes data on big game harvesting in British Columbia, Canada.  It uses the 1976--2018 dataset from https://catalogue.data.gov.bc.ca/dataset/big-game-harvest-statistics-1976-2018  I used the .xlsx version of the dataset rather than the .csv version, because the csv had half the header text cut off and does not have descriptions of field codes.

Annual population of BC from:  https://www2.gov.bc.ca/gov/content/data/statistics/people-population-community/population/population-estimates

Hunting licence sales from:
https://catalogue.data.gov.bc.ca/dataset/hunting-sales-statistics-2005-2019

BC Wildlife management units from:
https://catalogue.data.gov.bc.ca/dataset/wildlife-management-units

Population estimates:
GRIZZLY BEAR:  bc_grizzly_population_estimates_2015_and_2018_by_gbpu_population_sub_units from https://catalogue.data.gov.bc.ca/dataset/grizzly-bear-population-estimates
MOOSE:  Kuzyk -- 2016 -- Provincial population and harvest estimates of moose in British Columbia
ELK:  here, but no public access:  https://catalogue.data.gov.bc.ca/dataset/elk-cervus-elaphus-populations-scale-1-250-000
MULE DEER:  maybe in the aerial survey of large mammals, but access restricted:  https://catalogue.data.gov.bc.ca/dataset/aerial-survey-large-mammals-1994-1997
CARIBOU:  herd locations:  https://catalogue.data.gov.bc.ca/dataset/caribou-herd-locations-for-bc
WILDLIFE SPECIES INVENTORY:  https://catalogue.data.gov.bc.ca/dataset/wildlife-species-inventory-results-by-area-all

Author:  Heather More
Started:  2020-11-24 

NOTES:
https://stackoverflow.com/a/4714080
- @ accesses a slot in an S4 object like an object in spatialPolygons class.  Find slot names using slotNames(spPolygonObjectName).  Find contents of a slot using slot(spPolygonObjectName, "slotName").
- $ accesses a named variable in an S4 object or a dataframe or a list
- BC government has a Shiny app for this data at:  https://kootenaywildlife.shinyapps.io/BCHarvestData/
- Francis Iredale (via Jim Gnapp) suggests for species population data:
http://a100.gov.bc.ca/pub/siwe/search_reset.do
https://a100.gov.bc.ca/pub/clir/enterCLIR.do?redirect=Y

TODO:
- subdivide region 7

http://www.env.gov.bc.ca/fw/wildlife/management-issues/docs/kootenay_mule_deer_faq.pdf
try getting population data from here:  http://a100.gov.bc.ca/pub/siwe/search_reset.do
BC hunter expenditure survey:  http://www.env.gov.bc.ca/fw/wildlife/bc_hunt_value.html
BC harvest allocation policies:  http://www.env.gov.bc.ca/fw/wildlife/harvest_alloc/
region and wmu info:  https://www2.gov.bc.ca/gov/content/sports-culture/recreation/fishing-hunting/hunting/regulations-synopsis
BC regions map:  https://governmentofbc.maps.arcgis.com/home/webmap/viewer.html
BC data sets:  catalogue.data.gov.bc.ca/dataset
BC game management zones:  https://catalogue.data.gov.bc.ca/dataset/game-management-zones
-->

```{r}
# INPUTS
# Which species to plot
speciesToShow <- c("DEMU", "BEAB")#"ELK", "DEMU", "DEWT", "MOOS", "BEAB", "WOLF", "CARI", "GOAT", "SHEE", "BEAG", "COUG")
# Which WMU to plot -- as number, without dash, single digit as 0X
wmuToShow <- c(332)
# Which hunting region to plot -- as number, or as string if 7A or 7B
huntingRegionToShow <- c("7A")
# Choose to filter by province totals, hunting regions, or wmus
# Options:  "province", "huntingRegion", "wmu"
filterBy <- "wmu"
```

```{r}
# LOAD PACKAGES
library(readxl) # read Excel spreadsheets
library(tidyverse) # data manipulation
library(janitor) # data cleaning
library(leaflet)  # mapping
library(geojsonio)  # read geojson files
library(rmapshaper)  # simplify areas on maps
library(rgeos)  # functions for handling geographic regions
library(geosphere)  # functions for handling sperical regions (i.e. lat/long coordinages)
library(RColorBrewer)  # colour schemes
library(flexdashboard) # build output using knit button at top of RStudio
library(htmltools)  # HTML formatting for map labels

# CUSTOM FUNCTIONS
# Convert names of colours to hex
source("GetColourHex.R")
# Custom functions for this code
source("CustomFunctions.R")

# INPUT FILES
# Directory containing data
data_dir = "D:/Documents/Code/BC big game harvesting/data"
# Historical hunting kills
data_huntingKills <- list(
  "path" = data_dir,
  "fileName" = "big-game-harvest-statistics-1976-2018.xlsx",
  "sheetName" = "BGHS",
  "columnTypes" = c("numeric",  # hunt year
                     "text",  # species
                     "text",  # CI
                     "numeric",  # prov flag
                     "text",  # WMU
                     "text",  # region
                     rep("numeric", 14)  # remaining columns
                    )
)
# Historical population of BC
data_bcPopulation <- list(
  "path" = data_dir,
  "fileName" = "pop_bc_annual_estimates_clean.xlsx",
  "sheetName" = "data"
)
# Lists of WMUs and their corresponding hunting regions
data_wmuHuntingRegions <- list(
  "path" = data_dir,
  "fileName" = "conversions_hunting-region-wmus.xlsx",
  "sheetName" = "data",
  "columnTypes" = c("text",  # WMU id as string
                    "numeric",  # WMU id as int
                    "text",  # hunting region
                    "text"  # notes
                    )
)
# List of species included in the hunting dataset and their attributes
data_species <- list(
  "path" = data_dir,
  "fileName" = "conversions_species.xlsx",
  "sheetName" = "data"
)
# Map of WMUs
map_wmu <- list(
  "path" = data_dir,
  "fileName" = "wmu-map/WAA_WILDLIFE_MGMT_UNITS_SVW.geojson"
)

# LINKS
# Site to preview different basemaps:  http://leaflet-extras.github.io/leaflet-providers/preview/index.html
#tilesURL <- "http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}"
tilesURL <- "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
```

```{r}
# LOAD DATA

# Hunting kills
df_huntingKills <- ReadExcel(data_huntingKills)

# BC population
df_pop <- ReadExcel(data_bcPopulation)

# Conversions between WMU numbers and hunting regions
df_conversions <- ReadExcel(data_wmuHuntingRegions)

# Species names and characteristics
df_species <- ReadExcel(data_species)

# Map of wildlife management units
# https://rstudio.github.io/leaflet/json.html
# 4,535,784 bytes
wmus <- geojsonio::geojson_read(file.path(map_wmu[["path"]], map_wmu[["fileName"]], 
                           fsep = .Platform$file.sep), what = "sp")
# Simplify boundaries so they render faster
# 963,312 bytes
wmus <- rmapshaper::ms_simplify(wmus)

```
```{r}
# FUNCTIONS

# Look up full name of species based on code
# Input is species code as string, e.g. "BEAB"
# Output is species name as string, e.g. "Black bear"
GetSpeciesName <- function(speciesCode) {
  species_name <- df_species %>% 
    filter(code==speciesCode) %>% 
    pull(name)
  return(species_name)
}

# Find colour corresponding to species
# Input is species code as string, e.g. "BEAB"
# Output is colour as hex string, e.g. "#000000"
GetSpeciesColour <- function(speciesCode) {
  species_colour <- df_species %>% 
    filter(code==speciesCode) %>% 
    pull(colour) %>% 
    GetColourHex()
  return(species_colour)
}

# Plot style
# Input is ggplot object
# No output, just modifies plot aesthetics etc.
```

```{r}
# INVESTIGATE DATA
print(paste("Hunt years:  ", 
            paste(min(df_huntingKills$hunt_year)), 
            "--", 
            paste(max(df_huntingKills$hunt_year)), 
            collapse = ''
            )
      )
print(paste('Species:  ', 
            paste(lapply(unique(df_huntingKills$species), GetSpeciesName), 
                  collapse = ', ')
            )
      )
print(paste('WMUs:  ', 
            paste(length(unique(df_huntingKills$wmu)))
            )
      )
print(paste('Regions:  ', 
            paste(length(unique(df_huntingKills$region)))
            )
      )
```

```{r}
# FILTER

# Filter hunting data by selected region(s) and species
# Filter by region to show -- whole-province, selected WMU(s), or selected hunting region(s)
# df_huntingKills$prov_flag
#     9 for whole-province data
#     0 otherwise
# df_huntingKills$wmu
#     999 for whole-province data
#     X00 for all of region X
#     7A or 7B for all of region 7A or 7B
if (filterBy=="province") {
  df_filtered <- df_huntingKills %>% 
    filter(prov_flag==9)
} else if(filterBy=="huntingRegion") {
  if(is.character(huntingRegionToShow)) {
    df_filtered <- df_huntingKills %>% 
      filter(wmu==huntingRegionToShow)
  } else if (is.numeric(huntingRegionToShow)) {
    df_filtered <- df_huntingKills %>% 
      filter(wmu==(100*huntingRegionToShow + 99))
  }
} else if(filterBy=="wmu") {
  df_filtered <- df_huntingKills %>% 
    filter(wmu==wmuToShow)
}
# Filter by species to show
df_filtered <- df_filtered %>% 
  filter(species %in% speciesToShow)

# Filter population data so years match hunting data
df_pop_years <- df_pop %>% 
  filter(year >= min(df_filtered$hunt_year) 
         & year <= max(df_filtered$hunt_year)) %>% 
  rename(population_human = population)
```

```{r}
# ADD OTHER VARIABLES OF INTEREST TO DATAFRAME

# Add population data
df_filtered <- df_filtered %>% 
  left_join(df_pop_years, by = c("hunt_year" = "year"))

# Do some calculations
df_filtered <- df_filtered %>% 
  rowwise() %>% # sum over each row:  https://stackoverflow.com/a/33806717
  mutate(
    total_kills = sum(resident_kills, non_resident_kills, na.rm=TRUE),
    total_hunters = sum(resident_hunters, non_resident_hunters, na.rm=TRUE),
    total_days = sum(resident_days, non_resident_days, na.rm=TRUE),
    kills_per_hunter = total_kills/total_hunters,
    days_per_hunter = total_days/total_hunters,
    days_per_kill = total_days/total_kills)
```






```{r}
# Location of data
dataPath  <- "D:/Documents/Code/BC big game harvesting/data"
harvestName  <- "big-game-harvest-statistics-1976-2018.xlsx"
dataSheetName <- "BGHS"  # data
dataColumnTypes <- c("numeric", # hunt year
                     "text", # species
                     "text", # CI
                     "numeric", # prov flag
                     "text", # WMU
                     "text", # region
                     rep("numeric", 14)) # remaining columns
bcPopName <- "pop_bc_annual_estimates_clean.xlsx"
popDataSheetName <- "data"
wmuName <- "wmu-map/WAA_WILDLIFE_MGMT_UNITS_SVW.geojson"
wmuRegionConversionName <- "conversions_hunting-region-wmus.xlsx"
conversionSheetName <- "data"
conversionColumnTypes <- c("text", "numeric", "text", "text")
# Site to preview different basemaps:  http://leaflet-extras.github.io/leaflet-providers/preview/index.html
#tilesURL <- "http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}"
tilesURL <- "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"

# Which species to plot
speciesToShow <- c("DEMU", "BEAB")#"ELK", "DEMU", "DEWT", "MOOS", "BEAB", "WOLF", "CARI", "GOAT", "SHEE", "BEAG", "COUG")
# Which WMU to plot -- as number, without dash, single digit as 0X
wmuToShow <- c(735)
# Which hunting region to plot -- as number, or as string if 7A or 7B
huntingRegionToShow <- c("7A")
# Choose to filter by province totals, hunting regions, or wmus
# Options:  "province", "huntingRegion", "wmu"
filterBy <- "huntingRegion"

# Manually define species based on info in xlsx:  https://stackoverflow.com/a/10679467
# Get a list of all species codes by:  names(species_defs)
# Access a species name by:  species_defs[["CODE"]]
species_defs <- list(
  "ELK" = "Elk",
  "DEMU" = "Mule deer",
  "DEWT" = "White-tailed deer",
  "MOOS" = "Moose",
  "BEAB" = "Black bear",
  "WOLF" = "Wolf",
  "CARI" = "Caribou",
  "GOAT" = "Goat",
  "SHEE" = "Sheep",
  "BEAG" = "Grizzly bear",
  "COUG" = "Cougar"
)
# Function to look up full name of species based on code
GetSpeciesName <- function(speciesCode) {
  species_name <- species_defs[[speciesCode]]
  return(species_name)
}

# Colours for plotting
species_colours <- list(
  "MOOS" = "pink", # "Moose",
  "ELK" = "rust", # "Elk",
  "CARI" = "gold2", # "Caribou",
  "DEMU" = "yellow2", # "Mule deer",
  "DEWT" = "yellow", # "White-tailed deer",
  
  "GOAT" = "light green", # "Goat",
  "SHEE" = "dark green", # "Sheep",
  
  "BEAB" = "black", # "Black bear",
  "BEAG" = "grey", # "Grizzly bear",
  
  "WOLF" = "light blue", # "Wolf",
  
  "COUG" = "dark blue" # Cougar"
)
# Function to look up full name of species based on code
GetSpeciesColour <- function(speciesCode) {
  species_colour <- GetColour(species_colours[[speciesCode]])
  return(species_colour)
}

```

```{r}
# Read in data
df <- read_xlsx(file.path(dataPath, harvestName, 
                           fsep = .Platform$file.sep), 
                sheet = dataSheetName,
                col_types = dataColumnTypes # specify type of data in each column, or it will use logical for some
                ) %>% 
  clean_names()  # make column names nice

df_pop <- read_xlsx(file.path(dataPath, bcPopName, 
                           fsep = .Platform$file.sep),
                    sheet = popDataSheetName) %>% 
  clean_names()  # make column names nice

# Investigate data
print(paste("Hunt years:  ", paste(min(df$hunt_year)), "--", paste(max(df$hunt_year)), collapse = ''))
print(paste('Species:  ', paste(lapply(unique(df$species), GetSpeciesName), collapse = ', ')))
print(paste('WMUs:  ', paste(length(unique(df$wmu)))))
print(paste('Regions:  ', paste(length(unique(df$region)))))

# Filter dataframe for data of interest
if (filterBy=="province") {
  # Find number of rows that report data for entire province
  #unique(df$prov_flag)  # options are 0 or 9
  #unique(df_province$wmu)  # all wmu values are 999 for province data
  # wmu values are X00 for all of region X
  # wmu values are 7A or 7B for all of region 7A or 7B
  df_filtered <- df %>% filter(prov_flag==9)
} else if(filterBy=="huntingRegion") {
  if(is.character(huntingRegionToShow)) {
    df_filtered <- df %>% filter(wmu==huntingRegionToShow)
  } else if (is.numeric(huntingRegionToShow)) {
    df_filtered <- df %>% filter(wmu==100*huntingRegionToShow+99)
  }
} else if(filterBy=="wmu") {
  df_filtered <- df %>% filter(wmu==wmuToShow)
}

# Conversions between WMU numbers and hunting regions
df_conversions <- read_xlsx(file.path(dataPath, wmuRegionConversionName, 
                           fsep = .Platform$file.sep), 
                sheet = conversionSheetName,
                col_types = conversionColumnTypes
                )

```

```{r}
# Get data for plots
# to_plot <- df_province %>% 
# to_plot <- df_wmu %>% 
to_plot <- df_filtered %>% 
  filter(species %in% speciesToShow) %>% 
  rowwise() %>% # sum over each row:  https://stackoverflow.com/a/33806717
  mutate(
    total_kills = sum(resident_kills, non_resident_kills, na.rm=TRUE),
    total_hunters = sum(resident_hunters, non_resident_hunters, na.rm=TRUE),
    total_days = sum(resident_days, non_resident_days, na.rm=TRUE),
    kills_per_hunter = total_kills/total_hunters,
    days_per_hunter = total_days/total_hunters,
    days_per_kill = total_days/total_kills)

df_pop_years <- df_pop %>% 
  filter(year >= min(to_plot$hunt_year) 
         & year <= max(to_plot$hunt_year)) %>% 
  rename(population_human = population)
to_plot <- to_plot %>% 
  left_join(df_pop_years, by = c("hunt_year" = "year"))  # https://dplyr.tidyverse.org/articles/two-table.html


```

```{r}
# PLOTTING FUNCTIONS

# Theme
UseTheme <- function() {
    theme_light()
}

# Line and point styles
FormatLines <- function() {
  geom_line()
}
FormatPoints <- function() {
  geom_point(size=2, alpha=0.7)
}

# Function to use species-specific colours
UseSpeciesColours <- function() {
     scale_colour_manual(
       name = "Species",  # legend title
       values = paste(lapply(speciesToShow, GetSpeciesColour)),  # colour hex values
       breaks = speciesToShow,  # species codes corresponding to each hex value
       labels = paste(lapply(speciesToShow, GetSpeciesName))  # species names for legend
     )
}

# Text identifying year range
YearRangeAsText <- function() {
   paste("from", 
         paste(min(df_filtered$hunt_year)), 
         "to", 
         paste(max(df_filtered$hunt_year))
   )
}
```

```{r}
# Total kills
plot_prov_species <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = total_kills, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Total # kills"),
       title = paste("Total kills", YearRangeAsText())
  )
print(plot_prov_species)
```


```{r}
# Total hunters
plot_prov_hunters <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = total_hunters, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Total # hunters"),
       title = paste("Total hunters", YearRangeAsText())
  )
print(plot_prov_hunters)
```


```{r}
# Avg kills per hunter
plot_prov_killsperhunter <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = kills_per_hunter, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Avg kills per hunter"),
       title = paste("Average kills per hunter", YearRangeAsText())
  )
print(plot_prov_killsperhunter)
```
```{r}
# Total hunting days
plot_prov_totaldays <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = total_days, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Total # hunting days"),
       title = paste("Total # hunting days", YearRangeAsText())
  )
print(plot_prov_totaldays)
```

```{r}
# Avg hunting days per hunter
plot_prov_daysperhunter <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = days_per_hunter, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Avg hunt days per hunter"),
       title = paste("Average # hunting days per hunter", YearRangeAsText())
  )
print(plot_prov_daysperhunter)
```

```{r}
# Avg hunting days per kill
plot_prov_daysperhunter <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = days_per_kill, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Avg hunt days per kill"),
       title = paste("Average # hunting days per kill", YearRangeAsText())
  )
print(plot_prov_daysperhunter)
```



```{r}
# Resident hunters of each species
plot_prov_speciesres <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = resident_hunters, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("# resident hunters"),
       title = paste("Resident hunters", YearRangeAsText())
  )
print(plot_prov_speciesres)
```

```{r}
# Non-resident hunters of each species
plot_prov_speciesnonres <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = non_resident_hunters, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("# non-resident hunters"),
       title = paste("Non-resident hunters", YearRangeAsText())
  )
print(plot_prov_speciesnonres)
```

```{r}
# Resident hunters of each species, normalized to BC population
plot_prov_speciesresfrac <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = resident_hunters/population_human, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("# resident hunters/total BC population"),
       title = paste("Resident hunters as fraction of BC population", YearRangeAsText())
  )
print(plot_prov_speciesresfrac)
```

```{r}
# Total resident and non-resident hunters
# Note that each individual hunter is probably counted multiple times, because a lot of them probably have more than one tag
hunters_residence <- df_filtered %>% 
  group_by(hunt_year) %>% 
  summarise(
    across(resident_hunters, sum, na.rm=TRUE),
    across(non_resident_hunters, sum, na.rm=TRUE),
  ) %>% 
  pivot_longer(cols = !hunt_year, names_to = "residency", values_to = "n_hunters") %>% 
  left_join(df_pop_years, by = c("hunt_year" = "year"))

plot_prov_totalresnonres <- ggplot(data = hunters_residence) +
  aes(x = hunt_year, y = n_hunters, color = residency) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  labs(x = paste("Year"),
       y = paste("# hunters"),
       title = paste("Total resident and non-resident hunters", YearRangeAsText())
  )
print(plot_prov_totalresnonres)
```



```{r}
plot_prov_totalresfrac <- ggplot(data = filter(hunters_residence, residency == "resident_hunters")) +
  aes(x = hunt_year, y = n_hunters/population_human) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  labs(x = paste("Year"),
       y = paste("# hunters/BC population"),
       title = paste("Total resident hunters as a fraction of BC population", YearRangeAsText())
  )
print(plot_prov_totalresfrac)
```

```{r}
plot_bcpop <- ggplot(data = df_pop_years) +
  aes(x = year, y = population_human) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  labs(x = paste("Year"),
       y = paste("BC population"),
       title = paste("BC population", YearRangeAsText())
  )
print(plot_bcpop)
```


```{r}
# Avg kills per hunter, separated by hunter residency
plot_prov_killsperhunter_resident <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = resident_kills/resident_hunters, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Avg kills per resident hunter"),
       title = paste("Average kills per resident hunter", YearRangeAsText())
  )
print(plot_prov_killsperhunter_resident)
```

```{r}
plot_prov_killsperhunter_nonresident <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = non_resident_kills/non_resident_hunters, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Avg kills per non-resident hunter"),
       title = paste("Average kills per non-resident hunter", YearRangeAsText())
  )
print(plot_prov_killsperhunter_nonresident)
```

```{r}
# Avg hunting days per kill, separated by hunter residency
plot_prov_daysperhunter_resident <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = resident_days/resident_kills, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Avg hunt days per kill"),
       title = paste("Average # hunting days per kill for resident hunters", YearRangeAsText())
  )
print(plot_prov_daysperhunter_resident)
```

```{r}
plot_prov_daysperhunter_nonresident <- ggplot(data = df_filtered) +
  aes(x = hunt_year, y = non_resident_days/non_resident_kills, color = species) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  UseSpeciesColours() +
  labs(x = paste("Year"),
       y = paste("Avg hunt days per kill"),
       title = paste("Average # hunting days per kill for non-resident hunters", YearRangeAsText())
  )
print(plot_prov_daysperhunter_nonresident)
```

```{r}
total_allspecies <- df_filtered %>% 
  group_by(hunt_year) %>% 
  summarise(
    across(resident_kills, sum, na.rm=TRUE),
    across(non_resident_kills, sum, na.rm=TRUE),
  ) %>% 
  pivot_longer(cols = !hunt_year, names_to = "residency", values_to = "n_kills")

plot_prov_totalkills <- ggplot(data = total_allspecies) +
  aes(x = hunt_year, y = n_kills, color = residency) +
  FormatLines() +
  FormatPoints() +
  UseTheme() +
  labs(x = paste("Year"),
       y = paste("Total kills"),
       title = paste("Total kills", YearRangeAsText())
  )
print(plot_prov_totalkills)
```


```{r}
**************START HERE
# Wildlife management units map
# https://rstudio.github.io/leaflet/json.html
# 4,535,784 bytes
wmus <- geojsonio::geojson_read(file.path(dataPath, wmuName, 
                           fsep = .Platform$file.sep), what = "sp")
# Simplify boundaries so they render faster
# 963,312 bytes
wmus <- rmapshaper::ms_simplify(wmus)

# Add field to data to separate region 7 into 7A and 7B
# Input:  WMU number as string
# Output:  Hunting region number as string
GetRegion <- function(wmuID) {
  regionString <- df_conversions %>% 
    filter(wmu_string==wmuID) %>% 
    pull(region)  # return column as a vector
  return(regionString)
}
wmu_region <- unlist(lapply(wmus$WILDLIFE_MGMT_UNIT_ID, GetRegion))
# c<-sort(unique(df$wmu))
# a<-sort(unique(df$region))
# b<-sort(unique(wmus$WILDLIFE_MGMT_UNIT_ID))
wmus@data$HUNTING_REGION <- wmu_region

# Check total areas add to area of BC (944,735 km^2)
# Note that the geojson areas include a bunch of water so we expect a higher estimate
#testarea <- sum(wmus$FEATURE_AREA_SQM/(1000^2))
# Show possible colour schemes
#display.brewer.all()
# Generate palette
colourPalette <- brewer.pal(length(unique(wmus$REGION_RESPONSIBLE)),
                         "Set2")
colourLevels <- unique(wmus$REGION_RESPONSIBLE)
mapColours <- colorFactor(
  palette = colourPalette,
  levels = colourLevels
  )
# Prepare labels
#https://stackoverflow.com/a/43155126
wmu_hover_labels <- lapply(seq(nrow(wmus)), function(x) {
  paste(
           paste("<b>WMU # ", wmus$WILDLIFE_MGMT_UNIT_ID[x], "</b>", sep = ''),
           paste(format(
             round(as.numeric(wmus$FEATURE_AREA_SQM[x]/(1000^2)), 1),
             nsmall = 1,
             big.mark = ","
             ), "km^2"),  # https://stackoverflow.com/a/29465942
           paste("Game management zone: ", wmus$GAME_MANAGEMENT_ZONE_ID[x],
                 " (", wmus$GAME_MANAGEMENT_ZONE_NAME[x], ")",
                 sep = ''),
           paste("Hunting region: ", wmus$REGION_RESPONSIBLE[x],
                 " (", wmus$REGION_RESPONSIBLE_NAME[x], ")",
                 sep = ''),
         sep = "<br/>"
  )
})
wmu_static_labels <- lapply(wmus@polygons, function(x) {x@labpt}) %>% 
  unlist() %>% 
  matrix(., nrow = length(.), ncol = 2, byrow = TRUE) %>% 
  as_tibble() %>% 
  cbind(wmus$WILDLIFE_MGMT_UNIT_ID)
colnames(wmu_static_labels) <- c("long", "lat", "WMU")
  
# Show on map
leaflet(wmus) %>% 
  addTiles(tilesURL) %>% 
  addPolygons(stroke = TRUE,
              weight = 2,
              opacity = 1,
              fillOpacity = 0.4,
              color = ~mapColours(REGION_RESPONSIBLE),
              label = lapply(wmu_hover_labels, htmltools::HTML),
              labelOptions = labelOptions(
                direction = "top"),  # labels on hover:  https://stackoverflow.com/a/43155126
  highlight = highlightOptions(color = "red",
                                      fillColor = "red",
                                      weight = 2,
                                      bringToFront = TRUE)  # bring hovered-over polygon to front
  ) %>% 
  addLabelOnlyMarkers(data = wmu_static_labels,  # labels always on polygons
                      lng = ~long, 
                      lat = ~lat, 
                      label = ~WMU,
                      labelOptions = labelOptions(
                        noHide = TRUE, 
                        direction = 'auto', 
                        textOnly = TRUE,
                        style = list(
                          "color" = "grey"
                          )
                        )
                      )
# TODO:  add legend with hunting region colours
```

```{r}
# Show hunting regions on map
# Get list of WMUs mapped to hunting regions
# WMUs ending in 00 denote values from that hunting region but unknown WMU
# WMUs ending in 99 denote totals for that hunting region
# WMU 999 is province-wide total
# wmu_regions <- df %>% 
#   select(wmu, region) %>% 
#   distinct()
# WMU codes in geojson are e.g. 1-1, 1-15, but in hunting data they are e.g. 101, 115
# regions <- wmu_regions[wmus$WILDLIFE_MGMT_UNIT_ID]

# https://gis.stackexchange.com/a/225731
#region1 <- gUnaryUnion(wmus[wmus@data$REGION_RESPONSIBLE == 1, ])
hunting_regions <- gUnaryUnion(wmus, id = wmus@data$HUNTING_REGION)
#plot(hunting_regions)
# Access area of each region
# UPDATE:  note that "area" in a polygon class is NOT the projected area, but rather a planar area measurement used to ensure smaller polygons are plotted after larger ones:  https://www.rdocumentation.org/packages/sp/versions/1.4-4/topics/Polygons-class
# Instead, from the rgeos package use gArea() (for projected coordinates) or from the geosphere package use areaPolygon() (for lat-long coordinates) (check the +proj= part of the SpatialPolygon file to find out which you are using):  https://stackoverflow.com/a/8708828

# GetArea <- function(x) {
#   x@area
# }
hunting_region_areas <- areaPolygon(hunting_regions)/(1000^2) #sapply(hunting_regions@polygons, GetArea)
wmu_hover_labels <- lapply(seq(nrow(wmus)), function(x) {
  paste(
           paste("<b>WMU # ", wmus$WILDLIFE_MGMT_UNIT_ID[x], "</b>", sep = ''),
           paste(format(
             round(as.numeric(wmus$FEATURE_AREA_SQM[x]/(1000^2)), 1),
             nsmall = 1,
             big.mark = ","
             ), "km^2"),  # https://stackoverflow.com/a/29465942
           paste("Game management zone: ", wmus$GAME_MANAGEMENT_ZONE_ID[x],
                 " (", wmus$GAME_MANAGEMENT_ZONE_NAME[x], ")",
                 sep = ''),
           paste("Hunting region: ", wmus$REGION_RESPONSIBLE[x],
                 " (", wmus$REGION_RESPONSIBLE_NAME[x], ")",
                 sep = ''),
         sep = "<br/>"
  )
})

# Prepare labels
# Find coordinates of centroid of each region:  https://gis.stackexchange.com/a/43558
hunting_region_static_labels <- gCentroid(hunting_regions, byid = TRUE) %>% 
  as_tibble() %>% 
  cbind(seq(length(hunting_regions)))
colnames(hunting_region_static_labels) <- c("long", "lat", "hunting_region")
***************STARTHERE
# Colours
# Add data fields to the SpatialPolygons object, making it into a SpatialPolygonsDataFrame
# https://willchernoff.com/2012/10/08/add-attribute-data-to-object-of-class-spatialpolygonsdataframe-in-r/
# To get polygon IDs:  https://r.789695.n4.nabble.com/How-extract-the-names-of-ID-in-SpatialPolygons-object-td790614.html
hunting_regions_data <- tibble(
  sapply(slot(hunting_regions, "polygons"), function(x) slot(x, "ID"))  # polygon IDs
)
colnames(hunting_regions_data) = "polygon_id" 
hunting_regions_data <- hunting_regions_data %>% 
  mutate(polygon_colour = mapColours(polygon_id))
hunting_regions_spolydf <- SpatialPolygonsDataFrame(hunting_regions, hunting_regions_data)

# Show on map
leaflet(hunting_regions_spolydf) %>% 
  addTiles(tilesURL) %>% 
  addPolygons(stroke = TRUE,
              weight = 2,
              opacity = 1,
              fillOpacity = 0.4,
              color = ~polygon_colour,
              # popup = ~paste(sep = "<br/>",
              #                paste("<b>Hunting region: ", ID, 
              #                      " (", ID, ")", "</b>",
              #                      sep = '')
              # ),
              highlight = highlightOptions(color = "red",
                                                  fillColor = "red",
                                                  weight = 2,
                                                  bringToFront = TRUE)  # bring hovered-over polygon to front
              ) %>% 
  addLabelOnlyMarkers(data = hunting_region_static_labels,  # labels always on polygons
                      lng = ~long, 
                      lat = ~lat, 
                      label = ~hunting_region,
                      labelOptions = labelOptions(
                        noHide = TRUE, 
                        direction = 'auto', 
                        textOnly = TRUE,
                        style = list(
                          "color" = "grey"
                          )
                        )
                      )
```

